name: CI

on: push

env:
  APK_PATH: '/app/platforms/android/app/build/outputs/apk/debug'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: make install
      - name: Run Clean
        run: make clean
      - name: Run Build
        run: make build
      - name: Create artifacts
        uses: actions/upload-artifact@v2
        with:
          name: apk
          path: ${{ env.APK_PATH }} 

  release:
    if: startsWith(github.ref, 'refs/tags')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download binaries artifact
        uses: actions/download-artifact@v2
        with:
          name: apk
          path: ${{ env.APK_PATH }} 
      - name: Upload apk to release assets
        run: |
          set -x
          tag_name="${GITHUB_REF##*/}"
          assets=()
          for binary in ${APK_PATH}/*.apk; do
            assets+=("-a" "${binary}")
          done
          hub release edit "${assets[@]}" -m "$tag_name" "$tag_name"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
